apps/geral/urls.py
from django.urls import path
from . import views


app_name = 'geral'


urlpatterns = [
    path('nova-oficina/', views.nova_oficina, name='nova_oficina'),
    path('oficinas/', views.lista_oficina, name='lista_oficina'),
    path('excluir-oficina/<int:pk>/', views.excluir_oficina, name='excluir_oficina'),
    path('editar-oficina/<int:pk>/', views.editar_oficina, name='editar_oficina'),
    
    path('nova-oficina/', views.nova_oficina, name='nova_oficina'),
    path('oficinas/', views.lista_oficina, name='lista_oficina'),
    path('excluir-oficina/<int:pk>/', views.excluir_oficina, name='excluir_oficina'),
    path('editar-oficina/<int:pk>/', views.editar_oficina, name='editar_oficina'),
]

oficina/urls.py
from django.contrib import admin
from django.urls import path, include
# from apps.usuarios import views

urlpatterns = [
    path('usuarios/', include('usuarios.urls', namespace='usuarios')),
    path('admin/', admin.site.urls),
    path('', include('geral.urls', namespace='geral')),
]

apps/geral/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
# Create your models here.

class Oficina(models.Model):
    usuario = models.ForeignKey(User, verbose_name='Usuário', on_delete=models.CASCADE)
    nome = models.CharField(verbose_name='Nome', max_length=100)
    cnpj = models.CharField(verbose_name='CNPJ', max_length=18, blank=True, null=True)
    endereco = models.CharField(verbose_name='Endereço', max_length=200, blank=True, null=True)
    email = models.EmailField(verbose_name='E-mail', blank=True,null=True)
    telefone = models.CharField(verbose_name='Telefone', blank=True, null=True)
    
    def __str__(self) -> str:
        return self.nome
    
    def clean(self) :
        model = self.__class__
        if model.objects.count()> 0 and self.id != model.objects.get().id:
            raise ValidationError('Não é possivel cadastrar mais de uma oficina')
    
    class Meta:
        verbose_name = 'Oficina'
        verbose_name_plural = 'Oficinas'
        ordering =  ['nome']
        
        
class Mecanico(models.Model):
    usuario = models.ForeignKey(Oficina, verbose_name='Oficina', on_delete=models.CASCADE)
    nome = models.CharField(verbose_name='Nome', max_length=100)
    codigo = models.PositiveSmallIntegerField(verbose_name='Código')
    
    def __str__(self) -> str:
        return self.nome
    
    class Meta:
        verbose_name = 'Mecânico'
        verbose_name_plural = "Mecânicos"
        ordering = ['nome']

apps/geral/forms.py
from django import forms
from .models import  Oficina, Mecanico


class OficinaForm(forms.ModelForm):
    class Meta:
        model = Oficina
        exclude = ['usuario']
        
        
        
class MecanicoForm(forms.ModelForm):
    class Meta:
        model = Mecanico
        exclude = ['oficina']

apps/geral/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from .forms import OficinaForm , MecanicoForm
from .models import Oficina, Mecanico
# Create your views here.

# @login_required
def home(request):
    template_name = 'geral/home.html'
    context = {}
    return render(request, template_name, context)


@login_required
def nova_oficina(request):
    template_name = 'geral/nova_oficina.html'
    context = {}
    if request.method == 'POST':
        form = OficinaForm(request.POST)
        if form.is_valid():
           of = form.save(commit=False)
           of.usuario = request.user
           of.save()
           messages.success(request, 'Oficina cadastrada com suscesso.')
           return redirect('geral:lista_oficina')
       
        else:
            messagem_erro = list(form.erros.values())[0][0]
            messages.error(request, f'{messagem_erro}')
            return redirect ('geral:lista_oficina')
           
    form = OficinaForm()
    context['form'] = form
    return render(request, template_name, context)


def lista_oficina(request):
    template_name = 'geral/lista_oficina.html'
    oficinas = Oficina.objects.filter(usuario=request.user)
    context = {
        'oficinas': oficinas,
    }
    return render(request, template_name, context)

@login_required
def excluir_oficina(request,pk):
    oficina = get_object_or_404(Oficina, pk=pk) 
    oficina.delete()
    messages.info(request, 'Oficina excluida com sucesso.')
    return redirect('geral:lista_oficina')

@login_required
def editar_oficina(request, pk):
    template_name ='geral/nova_oficina.html'
    context={}
    oficina= get_object_or_404(oficina,pk=pk)
    if request.method == 'POST':
        form = OficinaForm(data=request.POST, instance=oficina)
        form.save()
        messages.sucess(request, 'Oficina editada com sucesso.')
        return redirect('geral:listaOficina')
    form= OficinaForm(instance=oficina)
    context['form'] =form
    return render (request, template_name, context)

@login_required
def novo_mecanico(request):
    template_name = 'geral/novo_mecanico.html'
    context = {}
    if request.method == 'POST':
        form = MecanicoForm(request.POST)
        if form.is_valid():
           mf = form.save(commit=False)
           mf.oficina = oficina
           mf.save()
           messages.success(request, 'Mecânico cadastrada com suscesso.')
           return redirect('geral:lista_mecanico')
    form= MecanicoForm()
    context['form'] = form
    return render (request, template_name, context)

login_required
def lista_mecanico(request):
    template_name = 'geral/lista_mecanico.html'
    oficina = get_object_or_404(Oficina, usuario=request.user)
    mecanicos = Mecanico.objects.filter(oficina=oficina)
    context= {
        'mecanicos':mecanicos
    }
    return render(request, template_name,context)

templates/geral/home.html
{% extends 'base.html' %}

{% block titulo %}
  Dashboard | {{ block.super }}
{% endblock titulo %}

{% block main %}
<main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
      <h1 class="h2">Dashboard</h1>
      {% include 'utils/messages.html' %}
    </div>
    {% include 'utils/messages.html' %}
  </main>
{% endblock main %}

templates/geral/lista_oficina.html
{% extends 'base.html' %}

{% block titulo %}
    Oficinas | {{ block.super }}
{% endblock titulo %}

{% block main  %}
    {% include 'utils/messages.html' %}
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">ID</th>
                <th scope="col">NOME</th>
                <th scope="col">CNPJ</th>
                <th scope="col">TELEFONE</th>
                <th scope="col" colspan='2'>AÇOES</th>
            </tr>

        </thead>
        <tbody>
            {% for oficina in oficinas %}
                <tr>
                    <th scope="row">{{ oficina.id }} </th>
                    <td>{{ oficina.nome }}</td>
                    <td>{{ oficina.cnpj }}</td>
                    <td>{{ oficina.telefone }}</td>
                    <td>
                        <a href='{% url "geral:editar_oficina" oficina.id %}' class='btn btn-outline-info btn-sm'>Editar</a>
                        <a href='{% url "geral:excluir_oficina" oficina.id %}' class='btn btn-outline-danger btn-sm'>Excluir</a>
                </tr>
            {% endfor %}    
        </tbody>
    </table>
    <a href='{% url "geral:nova_oficina" %}' class='btn btn-primary'>Nova<a/> 

{% endblock main %}

templates/geral/nova_oficina.html
{% extends 'base.html' %}
{% load widget_tweaks%}


{% block titulo %}
    Oficina | {{ block.super }}
{% endblock titulo %}

{% block main %}
    <form method="post">
        {% csrf_token %}
        <div class="mb-3">
            <label for="{{ form.nome.id_for_label }}" class="form-label">{{ form.nome.label}}</label>
            {% render_field form.nome class='form-control'  placeholder='Digite o nome da oficina...'%}
        </div>

        <div class="mb-3">
            <label for="{{ form.cnpj.id_for_label }}" class="form-label">{{ form.cnpj.label}}</label>
            {% render_field form.cnpj class='form-control'  placeholder='Digite o CNPJ da oficina...' %}
        </div>

        <div class="mb-3">
            <label for="{{ form.endereco.id_for_label }}" class="form-label">{{ form.endereco.label}}</label>
            {% render_field form.endereco class='form-control'  placeholder='Digite o endereco da oficina...' %}
        </div>

        <div class="mb-3">
            <label for="{{ form.email.id_for_label }}" class="form-label">{{ form.email.label}}</label>
            {% render_field form.email class='form-control'  placeholder='Digite o email da oficina...' %}
        </div>

        <div class="mb-3">
            <label for="{{ form.telefone.id_for_label }}" class="form-label">{{ form.telefone.label}}</label>
            {% render_field form.telefone class='form-control'  placeholder='Digite o telefone da oficina...' %}
        </div>
        
        <button type='submit' class="btn btn-primary">Adcionar</button>
        <a href="{% url 'geral:lista_oficina' %}" class="btn btn-outline-secondary">Cancelar</a>
 
        
    </form>
{% endblock main %}